#Week2 機械学習のための数学

##●行列積の実装


###【問題1】行列積を手計算する
AとBの行列積を手計算で解いてください。

計算過程もマークダウンテキストを用いて説明してください。

####【問題1 解答】
$$
\boldsymbol{A} =
\begin{bmatrix}
-1 & 2 & 3 \\
4 & -5 & 6 \\
7 & 8 & -9
\end{bmatrix}
\boldsymbol{B} =
\begin{bmatrix}
0 & 2 & 1 \\
0 & 2 & -8 \\
2 & 9 & -1
\end{bmatrix}\\
\begin{align}
\boldsymbol{AB} &=
\begin{bmatrix}
-1 \times 0\ + 2 \times 0\ + 3 \times 2 &  -1 \times 2\ + 2 \times 2\ + 3 \times 9 & -1 \times 1\ + 2 \times \bigl(-8 \bigr)\ + 3 \times \bigl(-1 \bigr) \\
4  \times 0\ - 5 \times 0\ + 6 \times 2 &  4  \times 2\ - 5 \times 2\ + 6 \times 9 &  4 \times 1\ - 5 \times \bigl(-8 \bigr)\ + 6 \times \bigl(-1 \bigr) \\
7  \times 0\ + 8 \times 0\ - 9 \times 2 &  7  \times 2\ + 8 \times 2\ - 9 \times 9 &  7 \times 1\ + 8 \times \bigl(-8 \bigr)\ - 9 \times \bigl(-1 \bigr) \\
\end{bmatrix}\\
&=
\begin{bmatrix}
6 & 29 & -20 \\
12 & 52 & 38 \\
-18 & -51 & -48
\end{bmatrix}
\end{align}
$$

###【問題2】NumPyの関数による計算
この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。


これらを使い行列積を計算してください。

In [1]:
import numpy as np

A_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
B_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

AB_ndarray = np.matmul(A_ndarray, B_ndarray)

print("AB=\n{}".format(AB_ndarray))


AB=
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


###【問題3】ある要素の計算を実装
手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。


行列Aの(0,0)の要素 
a
0
,
0
 と行列Bの(0,0)の要素 
b
0
,
0
 を掛け合わせる
行列Aの(0,1)の要素 
a
0
,
1
 と行列Bの(1,0)の要素 
b
1
,
0
 を掛け合わせる
行列Aの(0,2)の要素 
a
0
,
2
 と行列Bの(2,0)の要素 
b
2
,
0
 を掛け合わせる
それらの値をすべて足し合わせる

数式で表すと


2
∑
k
=
0
 
a
0
,
k
b
k
,
0

です。


この計算をnp.matmul()やnp.dot()、または@演算子を使わずに行うコードを書いてください。

In [2]:
AB_0_0 = 0    #行列ABの(0, 0)の要素

for k in range(A_ndarray.shape[1]):
    AB_0_0 += A_ndarray[0][k] * B_ndarray[k][0]
print("行列ABの(0, 0)= {}".format(AB_0_0))

行列ABの(0, 0)= 6


###【問題4】行列積を行う関数の作成
問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。


行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。


計算結果である 
3
×
3
 の行列Cの各要素 
c
i
,
j
 は数式で表すと次のようになります。

In [3]:
def compute_matrix_multiplication(arg_ndarray1, arg_ndarray2):
    '''
    #Description
        2つの行列のドット積を計算

    #Parameters
        arg_ndarray1:          行列1
        arg_ndarray2:          行列2

    #Returns
        ret_ndarray_answer:    行列1と行列2のドット積の結果
    '''

    num_row = arg_ndarray1.shape[0]    #計算結果の行列の行数（＝行列1の行数）
    num_col = arg_ndarray2.shape[1]    #計算結果の行列の列数（＝行列2の列数）

    ret_ndarray_answer = np.zeros(num_row* num_col).reshape(num_row, num_col)

    for i in range(num_row):
        for j in range(num_col):
            for k in range(arg_ndarray1.shape[1]):
                ret_ndarray_answer[i][j] += arg_ndarray1[i][k] * arg_ndarray2[k][j]
    return ret_ndarray_answer

AB_ndarray2 = compute_matrix_multiplication(A_ndarray, B_ndarray)
print("AB_ndarray2= \n{}".format(AB_ndarray2))

AB_ndarray2= 
[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


###【問題5】計算が定義されない入力を判定する
問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。


if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。

In [4]:
def compute_matrix_multiplication_ver2(arg_ndarray1, arg_ndarray2):
    '''
    #Description
        2つの行列のドット積を計算（各引数の行列の要素数が不当な場合は警告文を出力）

    #Parameters
        arg_ndarray1:          1番目の行列
        arg_ndarray2:          2番目の行列

    #Returns
        ret_ndarray_answer:    2つの行列のドット積の結果
    '''
    
    if(arg_ndarray1.shape[1] == arg_ndarray2.shape[0]):

        num_row_AB = arg_ndarray1.shape[0]
        num_col_AB = arg_ndarray2.shape[1]

        ret_ndarray_answer = np.zeros(num_row_AB* num_col_AB).reshape(num_row_AB, num_col_AB)

        for i in range(num_row_AB):
            for j in range(num_col_AB):
                for k in range(arg_ndarray1.shape[1]):
                    ret_ndarray_answer[i][j] += arg_ndarray1[i][k] * arg_ndarray2[k][j]
        return ret_ndarray_answer

    else:
        print("Warning: Invalid number of row and column are given!")
        print("         Matrix calculation is stopped!")

D_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
E_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

DE_ndarray = compute_matrix_multiplication_ver2(D_ndarray, E_ndarray)
print("DE_ndarray= \n{}".format(DE_ndarray))

         Matrix calculation is stopped!
DE_ndarray= 
None


###【問題6】転置
片方の行列を転置することで、行列積が計算できるようになります。


np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。

In [5]:
Et_ndarray = np.transpose(E_ndarray)
#Et_ndarray = E_ndarray.T
print("E_transposed= \n{}".format(Et_ndarray))

DEt_ndarray = compute_matrix_multiplication_ver2(D_ndarray, Et_ndarray)
print("DEt_ndarray= \n{}".format(DEt_ndarray))
#print("DEt_ndarray= \n{}".format(np.dot(D_ndarray, Et_ndarray)))

E_transposed= 
[[-9  6]
 [ 8 -5]
 [ 7  4]]
DEt_ndarray= 
[[ 46.  -4.]
 [-34.  73.]]
