#オブジェクト指向の活用

##【問題1】これまで利用してきたクラスの列挙
クラスを使う際はインスタンス化を行うことと、クラスの命名法がわかりました。この情報を元に、これまでの課題で利用してきたコードの中でどのようなクラスがあったかを答えてください。


Pandas、matplotlib、scikit-learnからそれぞれ1つ以上見つけてください。

###【問題1 解答】
- Pandas
      DataFrame, Series
- matplotlib
      Figure, Axes
- scikit-learn
      LogisticRegression, DecisionTreeClassifier

##【問題2】これまで利用してきたメソッドやインスタンス変数の列挙
これまでの課題で利用してきたコードの中でどのようなメソッドやインスタンス変数があったかを答えてください。


最低でもそれぞれ5つ以上答えてください。

###【問題2 解答】
1. DataFrameのメソッド
```
drop, sum, copy, head, discribe, isnull
```
2. DataFrameのインスタンス変数（Attribute）
```
loc, iloc, dtypes, columns, index, shape
```

##【問題3】標準化クラスをスクラッチで作成
理解をより深めるため、StandardScalerをスクラッチで作成しましょう。scikit-learnは使わず、NumPyなどを活用して標準化の計算を記述します。具体的にはfitメソッドとtransformメソッドを作ります。


今回は雛形を用意しました。クラスの作成方法は関数に近いです。メソッドはクラスの中にさらにインデントを一段下げて記述します。


インスタンス変数を作成する際はself.mean_のようにselfを付けます。クラスの外からscaler.mean_と書いていたscalerの部分が自分自身を表すselfになっています。

In [ ]:
class ScratchStandardScaler():
    """
    標準化のためのクラス
    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """
    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """
        self.mean_ =  X.mean(axis=0)  #平均（1 x n_featuresの行列）
        self.var_ =  X.var(axis=0)  #分散（1 x n_featuresの行列）
        
        return

    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量
        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        X_scaled = (X - self.mean_) / (self.var_)**(1/2)    #標準化

        return X_scaled


###動作確認###
import numpy as np

X = np.array([[1,2,3],
              [2,5,6],
              [2,5,6],
              [2,5,6],
              [2,5,6],
              [4,8,10]])
print("X:")
print(X)

#自作したStandardScalerを用いて標準化
sss = ScratchStandardScaler()
sss.fit(X)
X_scaled = sss.transform(X)
print("\n")
print("X_scaled:")
print(X_scaled)


#scikit-learnのStandardScalerを用いて標準化（比較用）
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X)
X_scaled_scikit = scaler.transform(X)

print("\n")
print("X_scaled_scikit:")
print(X_scaled_scikit)

#(X_scaled == X_scaled_scikit)
print("\n")
print("X_scaled == X_scaled_scikit:")
print(X_scaled == X_scaled_scikit)

X:
[[ 1  2  3]
 [ 2  5  6]
 [ 2  5  6]
 [ 2  5  6]
 [ 2  5  6]
 [ 4  8 10]]


X_scaled:
[[-1.29986737 -1.73205081 -1.55654065]
 [-0.18569534  0.         -0.08192319]
 [-0.18569534  0.         -0.08192319]
 [-0.18569534  0.         -0.08192319]
 [-0.18569534  0.         -0.08192319]
 [ 2.04264872  1.73205081  1.88423342]]


X_scaled_scikit:
[[-1.29986737 -1.73205081 -1.55654065]
 [-0.18569534  0.         -0.08192319]
 [-0.18569534  0.         -0.08192319]
 [-0.18569534  0.         -0.08192319]
 [-0.18569534  0.         -0.08192319]
 [ 2.04264872  1.73205081  1.88423342]]


X_scaled == X_scaled_scikit:
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
###動作確認###

import numpy as np
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]


#自作したStandardScalerを用いて標準化
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std_scratch = scratch_scaler.transform(X)
print("X_std_scratch:")
print(X_std_scratch)
print("\n")

#scikit-learnのStandardScalerを用いて標準化（比較用）
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)
print("平均 : {}".format(scaler.mean_))
print("分散 : {}".format(scaler.var_))
X_std_scikit = scaler.transform(X)
print("X_std_scikit:")
print(X_std_scikit)
print("\n")

#(X_std_scratch == X_std_scikit)
print("X_std_scratch == X_std_scikit:")
print(X_std_scratch == X_std_scikit)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
X_std_scratch:
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
X_std_scikit:
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0

##【問題4】 四則演算を行うクラスの作成
上記ExampleClassは足し算のメソッドを持っていますが、これに引き算、掛け算、割り算のメソッドを加えてください。


コンストラクタに入力されたvalueが文字列や配列など数値以外だった場合にはエラーを出すようにしてください。


クラス名や説明文も適切に書き換えてください。

In [49]:
class FourArithmeticOperator():
    """
    四則演算を行うクラス
    Parameters
    ----------
    value : float or int
        初期値
    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        if((type(value) == int) or (type(value) == float)):
            #コンストラクタの引数がint型またはfloat型の場合のみ、self.value変数に値をセット
            self.value = value
            print("初期値{}が設定されました".format(self.value))
        else:
            #コンストラクタの引数がint型・float型以外のデータ型のため、警告を出力
            print("Warning: {}型のデータが入力されました。int型またはfloat型の数値を入力してください!".format(type(value)))
            self.value = 0

    def add(self, value):
        """
        受け取った引数をself.valueに加える
        """
        print("{}に{}が足されました".format(self.value, value))
        self.value += value

    def subtract(self, value):
        """
        受け取った引数をself.valueから引く
        """
        print("{}から{}が引かれました".format(self.value, value))
        self.value -= value

    def multiply(self, value):
        """
        受け取った引数をself.valueに掛ける
        """
        print("{}に{}が掛けられました".format(self.value, value))
        self.value *= value

    def divide(self, value):
        """
        受け取った引数でself.valueを割る
        """
        print("{}が{}で割られました".format(self.value, value))
        self.value /= value

example = FourArithmeticOperator(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))
example.subtract(2)
print("value : {}".format(example.value))
example.multiply(10)
print("value : {}".format(example.value))
example.divide(3)
print("value : {}".format(example.value))

example = FourArithmeticOperator("dummy")

初期値5が設定されました
value : 5
5に3が足されました
value : 8
8から2が引かれました
value : 6
6に10が掛けられました
value : 60
60が3で割られました
value : 20.0
